[package]
name = "ntools"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.27", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4"
actix-cors = "0.6"
regex = "1"
